author: 唐胖子 # 作者
description: 唐胖子前端笔记
keyword: hexo-theme, vuejs

excerpt_link: Read more

menu:
  Home: /
  Series: /series/
  Tags: /tags/
  Archives: /archives/
  Projects: /projects/
  About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set utterances, gitment, uyan or disqus
comment: utterances

# utterances config
utterances_repo:                # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
gitment_owner: tonsliy
gitment_repo: tonsliy.github.io
gitment_oauth_id:
gitment_oauth_secret:

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about:
  banner: ""
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "The end is always near."
  weibo_username: 
  twitter_username: 
  github_username: tonsliy
  zhihu_username: tonsliy
  douban_username: tonsliy
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true

# China Registration
# e.g. 京ICP备12345678号-1
icp:
  enable: false
  number: 京ICP备12345678号-1 # e.g. 京ICP备12345678号-1
# e.g. 京公网安备 12345678901234号
ga:
  enable: false
  province: 京           # e.g. 京
  number: 12345678901234 # e.g. 12345678901234

